# Generated by Django 4.2.4 on 2023-12-17 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='caridade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caridade1.evento')),
            ],
        ),
    ]
