# Generated by Django 4.2.4 on 2024-01-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caridade1', '0002_alter_item_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reservado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caridade1.reservado'),
        ),
    ]
