# Generated by Django 4.2.4 on 2024-01-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caridade1', '0003_alter_item_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
